name: Master optimized builds

on:
  push:
    branches: [ master ]
    paths: [ 'src/**.rs', '.github/workflows/master-optimized-builds.yml' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        include:
          - os: windows-latest
            binary_path: target/release/dezoomify-rs.exe
          - os: macos-latest
            binary_path: target/release/dezoomify-rs
          - os: ubuntu-18.04
            binary_path: target/release/dezoomify-rs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release --locked
      - uses: actions/upload-artifact@v3
        with:
          name: dezoomify-rs ${{ matrix.os }}
          path: ${{ matrix.binary_path }}
  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: cd 'dezoomify-rs macos-latest' && chmod +x dezoomify-rs && tar --create --file dezoomify-rs-macos.tgz --gzip dezoomify-rs ../README-MACOS.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.sha }}
          name: Build ${{ github.sha }}
          body: This is a development build of dezoomify-rs.
          draft: false
          prerelease: true
          files: |
            dezoomify-rs windows-latest/dezoomify-rs.exe
            dezoomify-rs ubuntu-latest/dezoomify-rs
            dezoomify-rs macos-latest/dezoomify-rs-macos.tgz